services:
  ldg:
    build:
      context: .
    image: ldg:latest
    container_name: ${LDG_CONTAINER_NAME:-ldg}
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      - lee-net
      - lee-net-1

networks:
  lee-net:
    external: true
  lee-net-1:
    external: true
